### ISSUE TITLE
Update waku-simulator instance on every nwaku nightly release

### ISSUE THREAD

**Issue by alrevuelta** [waku-org/waku-simulator#19] opened 2024-02-19 09:09 UTC
Currently, we update waku-simulator on every new commit to nwaku master. Perhaps it would be better to do it on every nightly release (once a day) instead. Since each commit reboots the setup, that can affect the metrics, so frequent commits to master will leave some difficult to interpret metrics (crash? normal reboot due to new commit?, etc)

DoD
- [ ] Modify the action/hook so that waku-simulator instance is updated only on every nightly release instead of every commit.

**Comment by jakubgs** [comment] 2024-02-19 09:47
The current image looks new:
```
jakubgs@metal-01.he-eu-hel1.wakusim.misc:/docker/waku-simulator % d inspect wakuorg/nwaku:latest | grep -e created -e commit
        "Created": "2024-02-17T19:54:07.036907223Z",
                "commit": "ce151efc",
```
Did you do that?

**Comment by alrevuelta** [comment] 2024-02-19 10:26
cc @gabrielmer 

> Did you do that?

**Comment by jakubgs** [comment] 2024-02-19 10:41
Right, so is there anything more you need? It does seem to work as far as I can tell:
```
jakubgs@metal-01.he-eu-hel1.wakusim.misc:/docker/waku-simulator % j -o cat -u watchtower --since '1 days ago' --grep Creating | tail -n5
time="2024-02-18T17:50:20Z" level=info msg="Creating /waku-simulator_nwaku_78"
time="2024-02-18T17:50:21Z" level=info msg="Creating /waku-simulator_nwaku_29"
time="2024-02-18T17:50:22Z" level=info msg="Creating /waku-simulator_nwaku_93"
time="2024-02-18T17:50:23Z" level=info msg="Creating /waku-simulator_nwaku_1"
time="2024-02-18T17:50:24Z" level=info msg="Creating /waku-simulator_nwaku_85"
```

**Comment by jakubgs** [comment] 2024-02-19 10:47
BTW, Docker Hub images are synced with a delay, if you want the newest images faster you should use https://harbor.status.im/.

So `harbor.status.im/wakuorg/nwaku` and not just `wakuorg/nwaku`.

**Comment by jakubgs** [comment] 2024-02-19 10:51
I don't really see anything to do here, `watchtower` already updates images from the `latest` tag.

But just for good measure I added this pull to the compose for when the compose service is restarted:

- [`infra-role-compose-repo#f7c8f835`](https://github.com/status-im/infra-role-compose-repo/commit/f7c8f835) - service: add pull command before startup

**Comment by gabrielmer** [comment] 2024-02-19 10:53
> BTW, Docker Hub images are synced with a delay, if you want the newest images faster you should use https://harbor.status.im/.
> 
> So `harbor.status.im/wakuorg/nwaku` and not just `wakuorg/nwaku`.

How often are images synced in Dockerhub?

What we want to do here is to update the simulator's image only once a day.
The issue isn't just to have an updated image, it's also about not restarting the simulator too often with every new commit

**Comment by jakubgs** [comment] 2024-02-19 10:55
I checked and the Docker Hub sync is event-based, so the delay should be minimal:

![image](https://github.com/waku-org/waku-simulator/assets/2212681/a291bd4c-f7dc-429f-9f21-36d2171f770a)

**Comment by jakubgs** [comment] 2024-02-19 10:56
If you want the updates to happen less frequently we can simply not use `latest` image and instead build a special image for `wakusim` host on a different schedule from `master`. Every other day or whatever other option you prefer.

**Comment by jakubgs** [comment] 2024-02-19 10:57
Oh, an `latest` image is updated daily:

![image](https://github.com/waku-org/waku-simulator/assets/2212681/b17b66ed-0a90-4546-ae38-558679fbc06e)

Is that really too frequent?

**Comment by gabrielmer** [comment] 2024-02-19 11:03
> Oh, an `latest` image is updated daily:
> 
> ![image](https://private-user-images.githubusercontent.com/2212681/305925076-b17b66ed-0a90-4546-ae38-558679fbc06e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNDA3NjQsIm5iZiI6MTcwODM0MDQ2NCwicGF0aCI6Ii8yMjEyNjgxLzMwNTkyNTA3Ni1iMTdiNjZlZC0wYTkwLTQ1NDYtYWUzOC01NTg2NzlmYmMwNmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTlUMTEwMTA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjEzM2U5YzhkODQ0NTg0NGQ1ZmUxZTQ5MWRkNmU0NDBkOTEyMzI0ZTM3ZTZiYWQxMzE4OWYzMzU3MDczZjM4NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KEiHZt87OcqNwVqUO82wJnQq3TXmlKQrYLiqQkdK3SY)
> 
> https://ci.infra.status.im/job/nim-waku/job/docker-latest/configure
> 
> Is that really too frequent?

I think daily is what we were looking for, if so there's no issue and everything works perfectly.

@alrevuelta please confirm if there's anything else to do or we can close the issue

**Comment by jakubgs** [comment] 2024-02-20 10:00
I'm just going to close this, feel free to reopen.

**Closed by jakubgs** 2024-02-20 10:00 UTC
